/*!
* jquery.fn.dialog
* @author 浜戞贰鐒� http://qianduanblog.com
* @for ie9(鍚�)+銆乧hrome銆乫irefox
* @require http://static.qianduanblog.com/js/jquery-dialog/css/default.css
* @require drag.js
* @version 1.0
* 2013骞�9鏈�24鏃�10:31:37
*/
!function (a, b) { function c(b, c) { var d = b.data(e + "isOpen"), f = b.data(e + "isInit"), g = b.data(e + "options"), j = b.data(e + "id"); if (!d && f) { var k = a("#" + j), l = a("#" + j + "bg"), m = a(window).width(), n = a(window).height(), o = a(window).scrollLeft(), p = a(window).scrollTop(), q = k.width(), r = k.height(), s = (m - q) / 2 + o, t = (n - r) / 2 + p; 0 >= s && (s = 0), 0 >= t && (t = 0), k.css({ left: s, top: p - r, display: "block" }), i++, l.css("z-index", i).show().fadeTo(g.duration / 2, .5, function () { i++, k.css("z-index", i).animate({ top: t }, g.duration, function () { b.data(e + "isOpen", 1), h.push(j), a.isFunction(c) && c.call(k) }) }) } } function d(b, c) { var d = b.data(e + "isOpen"), f = b.data(e + "isInit"), g = b.data(e + "options"), i = b.data(e + "id"); if (d && f) { var j = a("#" + i), k = a("#" + i + "bg"), l = a(window).height(), m = a(window).scrollTop(), n = j.height(), o = l + m + n, p = a("html,body").css("overflow"); a("html,body").css("overflow", "hidden"), j.animate({ top: o }, g.duration, function () { a(this).hide(), k.fadeOut(g.duration / 2, function () { var d = a.inArray(i, h); b.data(e + "isOpen", 0), a("html,body").css("overflow", p), -1 != d && h.splice(d, 1), a.isFunction(c) && c.call(j) }) }) } } var e = "dialog____", f = 0, g = [], h = [], i = 2e3, j = { css: "http://static.qianduanblog.com/css/jquery-dialog/default.min.css", title: "Untitled", autoOpen: !1, width: "600px", height: "auto", duration: 123 }; a.fn.dialog = function (h) { return this.each(function () { var i, k, l, m, n = a(this), o = e + (new Date).getTime(), p = "<div style='position:absolute;' class='" + e + "' id='" + o + "'><div class='" + e + "wrap'><div class='" + e + "header'><span class='" + e + "title'></span><a class='" + e + "close' href='javascript:;'>&times;</a></div><div class='" + e + "body'></div></div></div>", q = "<div class='" + e + "bg' id='" + o + "bg'></div>"; n.data(e + "isInit") === b && n.data(e + "isInit", 0), n.data(e + "isOpen") === b && n.data(e + "isOpen", 0), l = n.data(e + "isInit"), m = n.data(e + "isOpen"), "open" === h ? c(n) : "close" === h ? d(n) : l || (i = a.extend({}, j, h), n.data(e + "isInit", 1), n.data(e + "id", o), n.data(e + "options", i), g.push(n[0]), f || (f = 1, i.css && (document.all ? document.createStyleSheet(i.css) : a("head").append('<link rel="stylesheet" href="' + i.css + '" />'))), $bg = a(q).appendTo("body"), k = a(p).appendTo("body"), k.find("." + e + "body").append(n), k.find("." + e + "title").html(i.title), k.css({ width: i.width, height: i.height }).hide(), n.show(), i.autoOpen && c(n), k.on("click", "." + e + "close", function () { d(n) }), console.log(k.css("position")), a.fn.drag && k.drag({ handle: "." + e + "header" })) }) }, a(document).keyup(function (b) { var c, f = h.length; 27 == b.which && f > 0 && (a(g).each(function () { return a(this).data(e + "id") == h[f - 1] ? void (c = a(this)) : void 0 }), d(c)) }) } (jQuery);